spring:
  thymeleaf:
    cache: false

  datasource:
    username: security
    password: security
    url: 'jdbc:h2:mem:security'
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
